apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-api
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-api
  template:
    metadata:
      labels:
        app: python-api
    spec:
      containers:
        - name: api
          image: python:3.9-slim
          command: ["python", "-m", "http.server", "8000"]
          ports:
            - containerPort: 8000
